// <auto-generated />
using System;
using GenshinApplication.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenshinApplication.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230319042538_moreTables")]
    partial class moreTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildCharacters", b =>
                {
                    b.Property<Guid>("BuildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharactersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BuildId", "CharactersId");

                    b.HasIndex("CharactersId");

                    b.ToTable("BuildCharacters");
                });

            modelBuilder.Entity("GenshinApplication.Models.Artifacts", b =>
                {
                    b.Property<Guid>("ArtifactsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Set")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetBonusOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetBonusTwo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtifactsId");

                    b.HasIndex("ItemId");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("GenshinApplication.Models.Build", b =>
                {
                    b.Property<Guid>("BuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CircletArtifactsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FlowerArtifactsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GobletArtifactsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlumeArtifactsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SandsArtifactsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WeaponId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BuildId");

                    b.HasIndex("CircletArtifactsId");

                    b.HasIndex("FlowerArtifactsId");

                    b.HasIndex("GobletArtifactsId");

                    b.HasIndex("PlumeArtifactsId");

                    b.HasIndex("SandsArtifactsId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Build");
                });

            modelBuilder.Entity("GenshinApplication.Models.Characters", b =>
                {
                    b.Property<Guid>("CharactersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Element")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfStars")
                        .HasColumnType("int");

                    b.Property<Guid?>("WeaponTypeWeaponId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CharactersId");

                    b.HasIndex("WeaponTypeWeaponId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GenshinApplication.Models.Items", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GenshinApplication.Models.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GenshinApplication.Models.Weapon", b =>
                {
                    b.Property<Guid>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Effect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WeaponId");

                    b.HasIndex("ItemId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("BuildCharacters", b =>
                {
                    b.HasOne("GenshinApplication.Models.Build", null)
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenshinApplication.Models.Characters", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenshinApplication.Models.Artifacts", b =>
                {
                    b.HasOne("GenshinApplication.Models.Items", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GenshinApplication.Models.Build", b =>
                {
                    b.HasOne("GenshinApplication.Models.Artifacts", "Circlet")
                        .WithMany()
                        .HasForeignKey("CircletArtifactsId");

                    b.HasOne("GenshinApplication.Models.Artifacts", "Flower")
                        .WithMany()
                        .HasForeignKey("FlowerArtifactsId");

                    b.HasOne("GenshinApplication.Models.Artifacts", "Goblet")
                        .WithMany()
                        .HasForeignKey("GobletArtifactsId");

                    b.HasOne("GenshinApplication.Models.Artifacts", "Plume")
                        .WithMany()
                        .HasForeignKey("PlumeArtifactsId");

                    b.HasOne("GenshinApplication.Models.Artifacts", "Sands")
                        .WithMany()
                        .HasForeignKey("SandsArtifactsId");

                    b.HasOne("GenshinApplication.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId");

                    b.Navigation("Circlet");

                    b.Navigation("Flower");

                    b.Navigation("Goblet");

                    b.Navigation("Plume");

                    b.Navigation("Sands");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("GenshinApplication.Models.Characters", b =>
                {
                    b.HasOne("GenshinApplication.Models.Weapon", "WeaponType")
                        .WithMany()
                        .HasForeignKey("WeaponTypeWeaponId");

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("GenshinApplication.Models.Weapon", b =>
                {
                    b.HasOne("GenshinApplication.Models.Items", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
